exports.seed = async function (knex) {
  await knex('users').insert([
    {
      id: 1,
      first_name: 'Jaelyn',
      last_name: 'Lee',
      age: '26',
      height: '158',
      weight: '50',
      target_weight: '48',
      workout_goal: 'gain muscle',
      fitness_level: '6',
    },
    {
      id: 2,
      first_name: 'John',
      last_name: 'Doe',
      age: '32',
      height: '175',
      weight: '80',
      target_weight: '75',
      workout_goal: 'lose weight',
      fitness_level: '4',
    },
    {
      id: 3,
      first_name: 'Emily',
      last_name: 'Smith',
      age: '29',
      height: '163',
      weight: '65',
      target_weight: '60',
      workout_goal: 'lose weight',
      fitness_level: '5',
    },
    {
      id: 4,
      first_name: 'Michael',
      last_name: 'Johnson',
      age: '35',
      height: '180',
      weight: '90',
      target_weight: '85',
      workout_goal: 'lose weight',
      fitness_level: '3',
    },
    {
      id: 5,
      first_name: 'Sophia',
      last_name: 'Brown',
      age: '31',
      height: '170',
      weight: '68',
      target_weight: '65',
      workout_goal: 'gain muscle',
      fitness_level: '7',
    },
    {
      id: 6,
      first_name: 'Ethan',
      last_name: 'Wilson',
      age: '28',
      height: '175',
      weight: '75',
      target_weight: '70',
      workout_goal: 'lose weight',
      fitness_level: '5',
    },
    {
      id: 7,
      first_name: 'Ava',
      last_name: 'Martinez',
      age: '27',
      height: '160',
      weight: '55',
      target_weight: '52',
      workout_goal: 'gain muscle',
      fitness_level: '8',
    },
    {
      id: 8,
      first_name: 'Noah',
      last_name: 'Taylor',
      age: '30',
      height: '185',
      weight: '85',
      target_weight: '80',
      workout_goal: 'lose weight',
      fitness_level: '4',
    },
    {
      id: 9,
      first_name: 'Olivia',
      last_name: 'Rodriguez',
      age: '33',
      height: '167',
      weight: '62',
      target_weight: '58',
      workout_goal: 'lose weight',
      fitness_level: '6',
    },
    {
      id: 10,
      first_name: 'Liam',
      last_name: 'Garcia',
      age: '29',
      height: '172',
      weight: '70',
      target_weight: '65',
      workout_goal: 'gain muscle',
      fitness_level: '7',
    },
  ])
}
